name: 'Check Pull Request Source'
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main # Apenas para PRs visando a main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        if: github.base_ref == 'main' && github.head_ref != 'dev'
        run: |
          echo "ERRO: Pull requests para a main só podem vir da branch 'dev'."
          exit 1